//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID_Document { get; set; }
        public int ID_User { get; set; }
        public int ID_departmentOrigin { get; set; }
        public int ID_departmentDestination { get; set; }
        public string Document_Name { get; set; }
        public string Description { get; set; }
    
        public virtual Deparment Deparment { get; set; }
        public virtual Deparment Deparment1 { get; set; }
        public virtual User User { get; set; }
    }
}
